### ISSUE TITLE
Update to 8.5.0 required

### ISSUE THREAD

**Issue by mfried40** [bdr99/node-mymazda#10]
Currently getting back the error message "An update to Mazda app is required to continue

**Comment by bdr99** [comment]
Thanks for letting me know, I'll publish a new version with the fix soon.

**Comment by mfried40** [comment]
I opened a pull request to fix it, I tested it and it works

**Comment by bdr99** [comment]
Thanks for the PR. I just merged it and released version 1.1.6 with the fix.
