### ISSUE TITLE
Engine State

### ISSUE THREAD

**Issue by hufftheweevil** [bdr99/node-mymazda#3]
Any idea how to determine engine state? From the raw API, `remoteInfos.BatteryStatus.EngineState` is always `3` for me - no matter if the engine is running or not. Is it supposed to be other numbers? It seems like it should be possible to determine if the car is on or off, since the app knows.

**Comment by bdr99** [comment]
Where in the app do you see the engine state? I don't see it anywhere, but maybe I missed it.

**Comment by hufftheweevil** [comment]
I was referring to the fact that the START button changes to a STOP button once you start it. But after another test, I now realize that it's not actually basing that off of any state.... It must just be using the fact that it received a confirmation that the request was received by the car. The test I just did was after starting the car with the app, waiting for the button to change to STOP, then closing and reopening the app. After reopening, the button says START because it lost it's own confirmation state. (And subsequently I have to go out to the car to stop it 🤦🏼‍♂️)

So disregard. But it is a shame that they have so much little detailed information available, but not that most basic data point.

**Comment by bdr99** [comment]
Closing since this is not an issue with `node-mymazda`.
