### ISSUE TITLE
TypeError: MyMazda is not a constructor

### ISSUE THREAD

**Issue by Kief5555** [bdr99/node-mymazda#7]
Seems like this is a certain `es` version issue. I just ran the test code.

Edit: Never Mind

**Comment by Kief5555** [comment]
Even an attempt of commonJs it returns that MyMazda is not a constructor.. im running node 18.2

**Comment by Kief5555** [comment]
Node 14 returns the same.

**Comment by Kief5555** [comment]
@bdr99

**Comment by Kief5555** [comment]
Node 12 seems to do the trick

```/Users/a/Desktop/Projects/CarProject /node_modules/node-mymazda/dist/MyMazdaAPIConnection.js:41
    return (responseBody?.state === "F" && typeof responseBody.errorCode === "number" && responseBody.errorCode !== 0);
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/l```

**Comment by bdr99** [comment]
Thanks for reporting this issue. I should have some time soon to look into this.

**Comment by Kief5555** [comment]
> Thanks for reporting this issue. I should have some time soon to look into this.

Do you need any more details?

**Comment by bdr99** [comment]
No, I don't need any details. I'll let you know if I do.

**Comment by Kief5555** [comment]
> No, I don't need any details. I'll let you know if I do.

Sounds good

**Comment by bdr99** [comment]
@Kief5555 I made some changes which should fix this issue. The newly published version 1.1.4 includes the fix. Can you please try the new version and let me know if it solves your issue?

**Comment by Kief5555** [comment]
> @Kief5555 I made some changes which should fix this issue. The newly published version 1.1.4 includes the fix. Can you please try the new version and let me know if it solves your issue?

Ok. Il test in about 8 hours

**Comment by Kief5555** [comment]
@bdr99,

Yep. It is all fine now. Before I close this issue - just a quick question. Is this safe to use? Do I risk Mazda locking my account or making any actions for this?

**Comment by bdr99** [comment]
Unfortunately, I can't make that guarantee. Only the people at Mazda would know for certain. However, I will say that I have been using this library (and the Python version [pymazda](https://github.com/bdr99/pymazda)) for over 2 years, and I've never experienced any repercussions from it, nor have I heard of anyone else who has. The requests made by the library are designed to mimic the MyMazda mobile app, so in theory, they should be indistinguishable from legitimate requests on Mazda's side.

**Comment by Kief5555** [comment]
> Unfortunately, I can't make that guarantee. Only the people at Mazda would know for certain. However, I will say that I have been using this library (and the Python version [pymazda](https://github.com/bdr99/pymazda)) for over 2 years, and I've never experienced any repercussions from it, nor have I heard of anyone else who has. The requests made by the library are designed to mimic the MyMazda mobile app, so in theory, they should be indistinguishable from legitimate requests on Mazda's side.

Ah. Good to know. Thanks!
