### ISSUE TITLE
An update to Mazda app is required to continue

### ISSUE THREAD

**Issue by abeggled** [bdr99/node-mymazda#8]
Since today, I've get the following error:

`Request failed: An update to Mazda app is required to continue`

Thanks in advance..

**Comment by abeggled** [comment]
@bdr99 please review and merge #9.

**Comment by 0151CALC** [comment]
I'm also getting the same error:

![image](https://user-images.githubusercontent.com/22921514/225902167-91cd4575-514a-4e33-ae25-405821c61e90.png)

**Comment by bdr99** [comment]
Thanks for reporting this. I published version 1.1.5 which should fix the issue.

**Comment by 0151CALC** [comment]
Hey, I seem to be getting the same error with version 1.1.5:

![image](https://user-images.githubusercontent.com/22921514/226422036-6f15b869-178e-4070-bcbe-19cc52446f2a.png)
![image](https://user-images.githubusercontent.com/22921514/226422086-b8236452-89dc-44bd-be4e-be352e8c543b.png)

Any idea what could cause this?
